namespace: everpure
name: flasharray
version: 1.44.0
readme: README.md
authors:
  - Everpure Ansible Team <pure-ansible-team@everpuredata.com>
description: Collection of modules to manage Everpure FlashArrays (including Cloud Block Store)
license:
  - GPL-3.0-or-later
  - BSD-2-Clause
tags:
  - everpure
  - purestorage
  - flasharray
  - cloudblockstore
  - storage
dependencies: {}
repository: https://github.com/Everpure-Ansible/FlashArray-Collection
documentation: https://github.com/Everpure-Ansible/FlashArray-Collection
issues: https://github.com/Everpure-Ansible/FlashArray-Collection/issues
build_ignore:
  - tests/integration
  - tests/unit
  - extensions/molecule
  - changelogs
  - docs
  - collections
  - .github
  - .ansible
  - .tox
  - .venv
  - .vscode
  - .pytest_cache
  - .pre-commit-config.yaml
  - settings.json
